### DISCUSSION TITLE
Can addonbar.uc.js become vertical with CSS?

### DISCUSSION THREAD

**Discussion by Pizzapops** [Aris-t2/CustomJSforFx#58] [General]
tkhquang was able to do a left/right vertical JS toolbar with CSS. Is this also possible with addonbar.uc.js?

I also have a question on line 24 in the script:
``js
tb_addonbar.setAttribute("toolboxid","rowser-bottombox");
``
Should the id be "browser-bottombox"?

**Comment by Aris-t2** [comment]
Thanks for the note, I lost the 'b' there. 

Yes, the add-on bar can be also vertical (either on the left of the right in this version):
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar_vertical.uc.js

**Comment by Pizzapops** [comment]
@Aris-t2 
Thanks for the link. A couple tweaks to the style, a CSS file for the classic buttons and I have replaced tkhquang's version.
![addonbar_v_mod](https://user-images.githubusercontent.com/33039961/46492911-8b5e3000-c7d4-11e8-9195-348fe64cb0d4.png)
Sidebar extension authors tend to forget things. Some do not provide toolbar buttons, Most of the extensions that do have a button, cannot toggle the sidebar to close.

**Comment by Pizzapops** [comment]
@Aris-t2 
You are one step ahead of me with the separators and spaces. Much better and more reliable than editing **perfs.js** !! The only thing I have run into is that spaces do not show up with addonbar_vertical. They do during customize but do not show afterwards. 

FYI: If the sidebar (bookmarks/history) is set to a minimum width, you can hide the addonbar_verticle by dragging the right side of the sidebar to the left. It takes a restart for it to reappear.

I have switched my bottom addonbar to the script version with no problems.

**Comment by Aris-t2** [comment]
They do for me with default files and included CSS code (see https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/space_and_separator_restorer.uc.js#L126).
![grafik](https://user-images.githubusercontent.com/6013569/46562098-e5591580-c8fa-11e8-885b-0f16e773da6e.png)

Test with unmodified files.

**Comment by Pizzapops** [comment]
Here is my results with current Nightly with unaltered scripts, No theme, NO extensions and NO CSSforFx. 
Customize screen:
![2018-10-06_js_customize](https://user-images.githubusercontent.com/33039961/46572594-67bef500-c94e-11e8-8a11-41dfad574441.png)
Results:
![2018-10-06_js_results](https://user-images.githubusercontent.com/33039961/46572597-74dbe400-c94e-11e8-8f9d-46e9ddf04438.png)
Spaces work in bottom addonbar but not in the vertical.

**Comment by Pizzapops** [comment]
@Aris-t2 
I found the spacer problem. The values in lines 130 and 131 (height & width) need to be swapped.

**Comment by Pizzapops** [comment]
My error. That only effects the separator.

**Comment by Pizzapops** [comment]
@Aris-t2 
Adding a toolbarspacer configuration fixes it for me.

``toolbar[orient="vertical"] toolbarspacer { \
		  -moz-appearance: none !important; \
		  height: 18px !important; \
		  width: 18px !important; \
		}\``

**Comment by Aris-t2** [comment]
My bad, I mistook spaces for separators. ;-)
A fixed version is already up.

**Comment by Pizzapops** [comment]
@Aris-t2 
I tweaked the vertical separator to closer match the horizontal. 2px, 2 color with opacity.

`toolbar[orient="vertical"] toolbarseparator { 
  -moz-appearance: none !important; 
  border-top: 1px solid rgba(15,17,38, 0.5) !important; 
  border-bottom: 1px solid rgba(255,255,255, 0.3) !important; 
  margin: 2px 2px !important; 
  height: 0px !important; 
  width: 18px !important; 
}`

**Comment by Acid-Crash** [comment]
Hi here.
Just tried to add addonbar_vertical.uc.js for the latest Nightly (method 2).
It becomes visible in "Customize..." window. 

However, I'm unable to place any buttons on it. Once I drag any button on it mouse-cursor changes and nothing happens.
Am I missing something?

**Comment by Pizzapops** [comment]
@Aris-t2 
Nightly 2018.11.14 broke addonbar, addonbar_v, and space/seperator bar. I haven't checked addonbar_top yet. The rest of the scripts seem to be OK.

**Comment by Aris-t2** [comment]
Not sure what Mozilla changed again.

Either `document.createXULElement("toolbar");` does not work properly for toolbars anymore or `CustomizableUI.registerArea("toolbarname", {legacy: true});` does not register the toolbar properly.

**Comment by Aris-t2** [comment]
Fixed version uploaded.

As it turns out toolbars require one more "registration" now `CustomizableUI.registerToolbarNode(toolbar);`
Thanks to Sören from Camp-Firefox for pointing this out.

https://bugzilla.mozilla.org/show_bug.cgi?id=1505734

**Comment by Acid-Crash** [comment]
Hi, it works now.
Small suggestion though.
On Nightly I've noticed that it lacks border on the right(if it is placed on the left).
Fixed this with
```border-right: 1px solid var(--sidebar-border-color) !important;```

Also Is it possible to add a "Toggle button" to the script that displays/hides the toolbar?

**Comment by Pizzapops** [comment]
@Aris-t2 
Your response time is again great. I theme modified CSS and all working. I agree with @Acid-Crash about border-right should be part of basic script.

**Comment by Aris-t2** [comment]
I will add the border style on next update and an optional toggle button, but a hidden toolbar will reappear on restart, because toggling only works temporarily and is not saved in an own pref. Will this be OK too?

**Comment by Acid-Crash** [comment]
@Aris-t2 sure. this will work.

**Comment by Acid-Crash** [comment]
@Aris-t2 
Just checked the update.
Is it possible to add "pressed" state for the toggle button when the toolbarbar is visible/enabled (the same was as regular sidebar toggle button behaves)?

**Comment by Aris-t2** [comment]
Yes, that is possible. Storing enabled/disabled pref is also possible.
Test the new version.

**Comment by Acid-Crash** [comment]
@Aris-t2 
Perfect. Thank you!

**Comment by Pizzapops** [comment]
@Aris-t2 
New version w/toggle tested and working fine. I changed the icon to the sync icon and rotated it 90deg. I use the sidebar toggle at the top of addonbar_v and it didn't look right with the addonbar toggle using the same icon above it. The sync icon seemed the most appropriate icon I could find in omni.ja.
![2018-11-15_152509](https://user-images.githubusercontent.com/33039961/48638460-537f0680-e996-11e8-9bca-f00b96b41831.jpg)
I was looking for something like this:
![v_toggle](https://user-images.githubusercontent.com/33039961/48638672-e455e200-e996-11e8-8560-0ff4fff6be1e.png)
Could back.svg or arrow-left.svg be used and be rotated 180deg when addonbar_v is hidden?

**Comment by Pizzapops** [comment]
@Aris-t2 
While tinkering with the **.toolbarbutton-icon**, I set the width to 0px. That gave me a narrow toggle button.  I moved the sidebar toggle next to it on the main toolbar and got the following results.
![2018-11-17_102037](https://user-images.githubusercontent.com/33039961/48663514-1169c980-ea57-11e8-8842-28fa5b7c8efd.jpg)
I realize this doesn't work for those not using buttons.

**Comment by Aris-t2** [comment]
@Pizzapops 
Regarding back/forward icons. We can only use one at a time. The left/right combo can be achieved like this:

```css
#tooglebutton_addonbar_v .toolbarbutton-icon {
  list-style-image: url("chrome://browser/skin/forward.svg");
  fill: red;
}
#tooglebutton_addonbar_v[checked] .toolbarbutton-icon {
  transform: rotate(180deg) !important; 
  fill: green; 
}
```

**Comment by Aris-t2** [comment]
CSS allows us to do stuff like this: 
![1](https://user-images.githubusercontent.com/6013569/48664645-16a03600-eaa2-11e8-9f95-c11de7a38381.png)

```css
#tooglebutton_addonbar_v .toolbarbutton-icon { 
  list-style-image: url("chrome://browser/skin/forward.svg"); 
  fill: red; 
} 
#tooglebutton_addonbar_v[checked] .toolbarbutton-icon { 
  fill: green;  
} 
#tooglebutton_addonbar_v { 
  background: url("chrome://browser/skin/back.svg") no-repeat; 
  background-size: 35% !important; 
  background-position: 10% 70% !important; 
} 
#tooglebutton_addonbar_v[checked] { 
  transform: rotate(180deg) !important;  
  background: url("chrome://browser/skin/back.svg") no-repeat; 
  background-position: 10% 30% !important; 
} 
```
Maybe its helpful for further tweaking.

**Comment by Pizzapops** [comment]
My latest toggle tweaking.
![toggle](https://user-images.githubusercontent.com/33039961/48872306-325f5100-edae-11e8-9089-781dad0859c2.png)
```css
if(addonbar_v_togglebutton) {
	  tooglebutton_addonbar_v_style ='
	  	 #tooglebutton_addonbar_v .toolbarbutton-icon {
 		  margin: -1px -6px !important;
 		  height: auto!important;
 		}
		#tooglebutton_addonbar_v {
  		  background: url("chrome://browser/skin/page-action.svg") no-repeat;
  		  background-size: 76% !important;
                  transform: rotate(90deg) !important;
  		  background-position: 50% 50% !important;
  		  fill:black !important;
		}\
		#tooglebutton_addonbar_v[checked] {
   		  fill:#4169E1 !important;
		}
	  ';
	}`

**Comment by Pizzapops** [comment]
@Aris-t2 
I have been using styling for the addonbars that is based on **buttons_on_bookmarks_toolbar_classic_appearance.css**. This has been working fine but I noticed that the buttons are larger than the buttons on the navigation toolbar.
standard compact mode   28px X 28px and 30px X 28px
more compact mode         26px X 26px and 28px X 26px
my classic compact mode   24px X 24px and 26px X 24Px
It is even more exaggerated in Normal and Touch modes (+4px).
Is this a Mozilla "feature"? Is there a way to compensate for it?

The compact classic styling requires some adjustment in the toolbar_v toggle (previous post). I also had to change the icon in **undo_closetab_button.uc.js**. undo.svg disappeared but other icons work fine.
```css
/* more compact classic navigation toolbar */
#main-window[uidensity=compact] {
  --toolbarbutton-inner-padding: 4px 4px!important;
}
#main-window[uidensity=compact] #nav-bar #nav-bar-overflow-button,
#main-window[uidensity=compact] #nav-bar #nav-bar-customization-target > toolbarbutton,
#main-window[uidensity=compact] #nav-bar #nav-bar-customization-target > toolbaritem textbox,
#main-window[uidensity=compact] #nav-bar #nav-bar-customization-target #stop-reload-button > toolbarbutton {
  margin: 0 !important;
  padding: 1px !important;
}
#main-window[uidensity=compact] #nav-bar #nav-bar-customization-target > toolbaritem {
  margin: 0 !important;
  padding: 1px !important;
}
/* fix for toolbar button badges */
#main-window[uidensity=compact] #nav-bar .toolbarbutton-1 .toolbarbutton-badge {
  -moz-margin-end: -5px !important;
}`

**Comment by Aris-t2** [comment]
I might be a Mozilla feature, but I believe you can control default paddings with default variables:

```css
:root {
  --toolbarbutton-outer-padding: 0px !important;
  --toolbarbutton-inner-padding: 0px !important;
}
```

The code in `buttons_on_bookmarks_toolbar_classic_appearance.css` seems to miss a `-moz-appearance: none !important;` on current Firefox versions. It will be fixed on next update.

```css
/* classic button style */
#main-window:not([customizing]) #PlacesToolbar .bookmark-item:not(menu):not(menuitem)[disabled=true]:-moz-any([open],[checked],:hover:active,:active),
#PlacesToolbar toolbarbutton[type="menu-button"],
#PlacesToolbar .bookmark-item:not(menu):not(menuitem) > .toolbarbutton-menubutton-button[open] + .toolbarbutton-menubutton-dropmarker > .dropmarker-icon,
#PlacesToolbar .bookmark-item:not(menu):not(menuitem)[open] > .toolbarbutton-menubutton-button,
#PlacesToolbar .bookmark-item:not(menu):not(menuitem)[open] > .toolbarbutton-menubutton-dropmarker > .dropmarker-icon,
#PlacesToolbar .bookmark-item:not(menu):not(menuitem):not([checked]):not([open]):not(:active),
#PlacesToolbar .bookmark-item:not(menu):not(menuitem):not([buttonover]):not([open]):not(:active) > .toolbarbutton-menubutton-dropmarker:not([disabled]) > .dropmarker-icon {
  -moz-appearance: none !important;
  background: rgba(151,152,153,.05) linear-gradient(rgba(251,252,253,.95), rgba(246,247,248,.47) 49%, 
			  rgba(231,232,233,.45) 51%, rgba(225,226,229,.3)) !important;
  border-color: rgba(0,0,0,.12) rgba(0,0,0,.19) rgba(0,0,0,.38) !important;
  box-shadow: 0 0 0 1px rgba(255,255,255,.3) inset,
			  0 0 0 2px rgba(255,255,255,.1) inset,
			  0 0 0 1px rgba(0,0,0,.4) inset !important;
}
```

**Comment by Pizzapops** [comment]
@Aris-t2 
Your root fix worked fine for Compact density but made Normal and Touch ugly.  I modified the general_variables.css to only affect the Compact density. The other densities are not a priority.
```css
\  #main-window[uidensity=compact]{
  --toolbarbutton-outer-padding: 0px !important;
  --toolbarbutton-inner-padding: 0px !important;
  }`

**Comment by Aris-t2** [comment]
Actually the code was no general fix, but just something to experiment with ;-)

**Comment by Pizzapops** [comment]
Time to tweak the toggle again. The **page-action.svg** seems to have been changed to **more.svg** but I can't get it to work with my earlier toggle post. To keep a narrow button, icon was change to **back-12.svg** with some code changes. 
![addonbar_v_toggle](https://user-images.githubusercontent.com/33039961/54946343-e2cc9580-4f05-11e9-8628-ef277fcb44c9.jpg)
```css 
        // style toggle button\
	if(addonbar_v_togglebutton) {
	  tooglebutton_addonbar_v_style ='\
	  	 #tooglebutton_addonbar_v .toolbarbutton-icon {\
 		  width: 12px!important;\
 		  height: 24px!important;\
 		  border-radius: 3px !important;\
 		}\
		#tooglebutton_addonbar_v {\
  		  background: url("chrome://browser/skin/back-12.svg") no-repeat; \
  		  background-size: 90% !important;\
                  transform: rotate(180deg) !important;\
  		  background-position: 50% 50% !important;\
  		  fill:#000000 !important;\
		}\
		#tooglebutton_addonbar_v[checked] {\
			transform: rotate(0deg) !important;\
   		    fill:#B40005 !important;\
		}\
    ';
	}`

**Comment by Pizzapops** [comment]
**addonbar_vertical does not collapse in Full Screen(F11).**

This happens with 66.0.2, Beta 67.0b5 and Nightly. Styling and icons no longer visable but a blank 30px left border remains. Deactivating the vertical toolbar via Customize gives the same results. I did a new Nightly setup with default theme, no extensions, no css mods, and the only script active was the current **addonbar_vertical.uc.js** . Same results. 

If I delete line 34 (**var addonbar_v_width = "30px"; // toolbar width**), the toolbar will collapse but it breaks styling.

**Comment by Aris-t2** [comment]
Posted a new file. ;-)

**Comment by Pizzapops** [comment]
All good now, Thanks!

**Comment by Altsinn** [comment]
Hi @Aris-t2, 
I want to ask if it is possible to make toggle button work with multiple windows? Currently when you open a second window and click the toggle button, the addon bar is hidden only in the first one. Additionally the button don't change its appearance from active to inactive (again, it happens only in the first window) . It will be neat if the hide/unhide status can be swiched globally for all open windows. 
Thanks!

**Comment by Aris-t2** [comment]
This looks like a bug to me. I will look into it.

**Comment by Altsinn** [comment]
> This looks like a bug to me. I will look into it.

Hi @Aris-t2, have you had a chance to check this out?

**Comment by Aris-t2** [comment]
I just uploaded a new version.

While button behavior could be slightly improved in a multi window environment, the script itself is very unstable. Sometimes it works as it should, sometimes is does not, no idea why. Hotkey / Ctrl+Alt+/ still is not working probably in a multi window environment.

**Comment by Pizzapops** [comment]
I just noticed that the side panel opens to the left of the vertical addon bar. This happens with Fx86, Beta & Nightly. ESR is probably OK because Waterfox G3.1.1 and Tor are not affected.
![2021-02-27_091257](https://user-images.githubusercontent.com/33039961/109391652-c1d50200-78dd-11eb-8fd3-74ae900ccbca.jpg)

**Comment by Aris-t2** [comment]
Enable "insert_before_borders" pref. The border items are gone, so vertical toolbar should become first item again.

**Comment by Pizzapops** [comment]
vertical addonbar is back where it belongs. Did require a couple Restarts. Thanks!!

**Comment by molio** [comment]
I want to put the vertical add-on bar to the right of the side panel, where should I change it?

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar_vertical.uc.js#L35

**Comment by molio** [comment]
Thanks for the response. But...

This will place the vertical add-on bar on the **right edge** of the browser.
Instead, we want to place it just to the **right of the side bar**(panel).
As shown in the following image.

![](https://user-images.githubusercontent.com/33039961/109391652-c1d50200-78dd-11eb-8fd3-74ae900ccbca.jpg)
.

https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar_vertical.uc.js#L71
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar_vertical.uc.js#L192
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar_vertical.uc.js#L205
I thought I could edit this area, but I couldn't figure it out. Sorry, sir.

**Comment by Aris-t2** [comment]
This should work inside `userChrome.css`:

```css
#sidebar-box {
  -moz-box-ordinal-group: 0 !important;
}
```

**Comment by molio** [comment]
@Aris-t2 Thank you! for your quick response.
It turned out as expected.

However, I also got greedy.
Is it possible to put two(vertical1, vertical2) bars on each side (left and right) of the side-bar(panel)?
Like a top-tool bar and an add-on bar.

**Comment by Aris-t2** [comment]
It should be possible, if you create a second version of the script file and modify vertical toolbars id.

**Comment by molio** [comment]
I modified 
`toolbox_abv` to `toolbox_abv86`,
`addonbar_v` to `addonbar_v86`, and 
`vaddonbar` to `vaddonbar86`.

Delete lines 192 to 198
```css
		#main-window:-moz-lwtheme #addonbar_v { \
		  background: var(--lwt-accent-color) !important; \
		} \
		#main-window[lwtheme-image="true"]:-moz-lwtheme #addonbar_v { \
		  background: var(--lwt-header-image) !important; \
		  background-position: 0vw 50vh !important; \
		} \
```
Deleted lines 221 to 224.
```css
		#addonbar_v toolbarbutton, \
		#addonbar_v toolbar .toolbarbutton-1 { \
		  padding: 0 !important; \
		} \
```

> This should work inside `userChrome.css`:
> 
> ```css
> #sidebar-box {
>   -moz-box-ordinal-group: 0 !important;
> }
> ```
I commented it out because I thought it would affect both bars if I specified it in the css.


Renamed the script file and created a second bar.
I'm not sure I understand it properly, but 
So far, it seems to be working, but if there is anything wrong, or if you have a more elegant (smart, intelligent ) way of doing it, please correct me.
 I would be happy to correct it.



![fxv2](https://user-images.githubusercontent.com/1826830/134963464-218c1591-d297-48d6-a368-702b11aa1705.png)

**Comment by molio** [comment]
Using **alice0775**'s userChrome.js, config.js, and config-prefs.js, only **verticalAddOnBar** behaves strangely when I use this script.

The **verticalAddOnBar** is placed on the right side of the sidebar and the width of the sidebar cannot be changed.

**Reply by molio** [reply]
Line 33.
insert_before_borders = false;
to
insert_before_borders = true;.

the sidebar will come to the left.

Line 19
init: function() {
to
init: function() {
document.getElementById('sidebar-splitter').setAttribute("resizebefore", "farthest");
document.getElementById('sidebar-splitter').setAttribute("resizeafter", "farthest");

I could resize the sidebar

**Reply by molio** [reply]
Because I don't think this change is the right one,
_I know I am being thick,_
Could you **please release** a version that supports **alice0775's loader**?

**Reply by molio** [reply]
Also because I want a second vertical bar beside the right side of the sidebar too, as I posted earlier in,
I renamed and copied the file and changed the Javascript class name and the DOM id and class name so they don't duplicate the original guy.

insert_before_borders = false;
as it is.

But the second bar appeared, but both bars were created on the left side of the sidebar

**Reply by molio** [reply]
I'm sure there is something wrong with my changes, but I can't tell any more with my knowledge.

I've been tricking myself into rewriting and adding a second one every time I change the script or Firefox, but I'm at my wit's end.

Again, I know I'm being presumptuous, but I'm going to make a request.

Please release an official vertical add-on bar beside the right side of the sidebar.

I sincerely hope so.

**Reply by Aris-t2** [reply]
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar_vertical.uc.js

![image](https://github.com/Aris-t2/CustomJSforFx/assets/6013569/01a4f557-467e-485f-ad76-8c6ab762a7e0)
![image](https://github.com/Aris-t2/CustomJSforFx/assets/6013569/2c0ab39a-4689-416e-a552-29586a53288d)

**Reply by Aris-t2** [reply]
I uploaded a new file. The vertical add-on bar now works on the left and on the right and with sidebar on the left and on the right.

**Reply by molio** [reply]
Thanks for the correction.
But isn't that the one who moved it to the far left?

My desire is for two on each side of the sidebar.
As shown in the diagram.

![](https://user-images.githubusercontent.com/1826830/134963464-218c1591-d297-48d6-a368-702b11aa1705.png)


Could you please add addonbar_vertical_R.uc.js?

**Reply by Aris-t2** [reply]
Assuming you created two vertical addon-bars using this projects version, you should be able to use CSS to move sidebars, toolbars in appcontent to a desired position.

1. everything on the right: browser content, vertical addon bar 1, sidebar, vertical addon bar 2

```css
#appcontent{
  order: 10 !important;
}

#toolbox_abv {
  order: 11 !important;
}

#sidebar-splitter{
  order: 12 !important;
}

#sidebar-box {
  order: 13 !important;
}

#toolbox_abv2 {
  order: 14 !important;
}
```

2. everything on the left: vertical addon bar 1, sidebar, vertical addon bar 2, browser content

```css
#toolbox_abv {
  order: 10 !important;
}

#sidebar-box {
  order: 11 !important;
}

#sidebar-splitter {
  order: 12 !important;
}

#toolbox_abv2 {
  order: 13 !important;
}

#appcontent{
  order: 14 !important;
}
```
