### DISCUSSION TITLE
Make urlbar results scrollable.

### DISCUSSION THREAD

**Discussion by mzso** [Aris-t2/CustomJSforFx#77] [Ideas]
Hi!
For a really long time if there were more results that what fit on the screen the urlbar results got a scrollbar, and I could scroll through all the results.
In contrast nowadays the extra results are off-screen and I can only select the completely blindly via the arrow keys, which is a ridiculous design choice by mozilla. (Also the one-click search buttons are also pushed off the screen, if someone wants them.)

Couldn't it be possible to the urbar results popup scrollable so more results could be viewed/used?

**Comment by Aris-t2** [comment]
The is a semi-working solution for this.

```css
.urlbarView {
  overflow-y: scroll !important;
  overflow-x: hidden !important;
  height: auto !important;
  max-height: 400px !important;
}
```

- scrollbar in results
- no autoscrolling, if navigating with keyboard through results
- the search engines area is only visible, if you scroll to the bottom

Adding the code to deeper results area will resolve above's search engines issue, but create another issue with results.
