### ISSUE TITLE
restart_item_in_menu.uc.js needs an update for Firefox 139

### ISSUE THREAD

**Issue by Speravir** [Aris-t2/CustomJSforFx#136]
In Firefox 139 the DOM structure for menus has been changed. This means that the CSS part of `restart_item_in_menu.uc.js` does not work anymore. And while there is an update anyway why not switching to template strings?

So, the changed text from [line 72](https://github.com/Aris-t2/CustomJSforFx/blob/0afe0834cd504027d10dc8ff0e1eea4d293710e9/scripts/restart_item_in_menu.uc.js#L72) to line 83 would be:
```css
	 menu_item_code =`
	  #fileMenu-restart-item {
	  	 list-style-image: url("${icon}") !important; /* File Menu Entry */
	  }
	  #fileMenu-restart-item > .menu-icon { /* Style the menuItem */
		 margin-inline-start: 2px;
		 margin-top: 2px;
		-moz-context-properties: fill;
		 transform: scaleX(-1);
		 fill: red;
	  }
	 `;
```
And from [line 88](https://github.com/Aris-t2/CustomJSforFx/blob/0afe0834cd504027d10dc8ff0e1eea4d293710e9/scripts/restart_item_in_menu.uc.js#L88) to line 99 which could be left unchanged in CSS, but for consistency I added one `>` before `.toolbarbutton-icon` in line 92:
```css
	 appmenu_item_code = `
	  #appMenu-restart-button {
		list-style-image: url("${icon}"); /* Button in appMenu */
	  }
	  #appMenu-restart-button > .toolbarbutton-icon { /* Style the Button */
		transform: scaleX(-1); /* Icon mirroring */
		color: red; /* Icon color name */
	  }
	  #main-window:-moz-lwtheme:-moz-lwtheme-brighttext #appMenu-restart-button .toolbarbutton-icon {
		color: unset; /* do not color the icon in dark mode */
	  }
	 `;
```
