### ISSUE TITLE
addonbar width and height auto expand with showiconbadge,is that feature?

### ISSUE THREAD

**Issue by GoogleBeEvil** [Aris-t2/CustomJSforFx#15]
when move ublock (check showIconBadge in ublock ) to addonbar,the height will expand,is it bug?

**Comment by GoogleBeEvil** [comment]
edit:if fixed the height by css ,the icon will be flat round

**Comment by Aris-t2** [comment]
Test this code:

```css
#addonbar toolbarbutton .toolbarbutton-icon {
  padding: 0 !important;
  width: 16px !important;
  height: 16px !important;
}

#addonbar .toolbarbutton-badge-stack {
  padding: 0 !important;
  margin: 0 !important;
  width: 16px !important;
  min-width: 16px !important;
  height: 16px !important;
  min-height: 16px !important;
}

#addonbar toolbarbutton .toolbarbutton-badge {
  margin-top: 0px !important;
  font-size: 8px !important;
}
```
