### ISSUE TITLE
can add  compact_buttons for addon_vertical script?

### ISSUE THREAD

**Issue by GoogleBeEvil** [Aris-t2/CustomJSforFx#26]
just like the  addonbar.uc.js

**Comment by Aris-t2** [comment]
Should be possible. Could you test this in userChrome.css:

```css
#addonbar_v toolbarbutton .toolbarbutton-icon { 
  padding: 0 !important; 
  width: 16px !important; 
  height: 16px !important; 
} 
#addonbar_v .toolbarbutton-badge-stack { 
  padding: 0 !important; 
  margin: 0 !important; 
  width: 16px !important; 
  min-width: 16px !important; 
  height: 16px !important; 
  min-height: 16px !important; 
} 
#addonbar_v toolbarbutton .toolbarbutton-badge { 
  margin-top: 0px !important; 
  font-size: 8px !important; 
} 
```

Does this look correct?
